#!/bin/bash

echo "🚀 TELUS AI Factory Docs - GitHub Pages Deployment"
echo ""
echo "Follow these steps:"
echo ""
echo "1️⃣  Create a new repository on GitHub:"
echo "   👉 https://github.com/new"
echo "   Name it: telus-ai-factory-docs"
echo "   Make it PUBLIC"
echo ""
echo "2️⃣  Copy your repository URL from GitHub"
echo ""
echo "3️⃣  Run these commands (replace YOUR-USERNAME):"
echo ""
echo "   git init"
echo "   git add -A"
echo "   git commit -m 'Initial commit: TELUS AI Factory Documentation'"
echo "   git remote add origin https://github.com/YOUR-USERNAME/telus-ai-factory-docs.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "4️⃣  Enable GitHub Pages:"
echo "   • Go to Settings > Pages"
echo "   • Source: GitHub Actions"
echo ""
echo "5️⃣  Your site will be live at:"
echo "   https://YOUR-USERNAME.github.io/telus-ai-factory-docs/"
echo ""
echo "✅ Everything is configured and ready!"
echo ""
